use_frameworks!

target 'WJPlayer_Example' do
  pod 'WJPlayer', :path => '../'

  target 'WJPlayer_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
